### ISSUE TITLE
log translate / enrichment seems not to work 

### ISSUE THREAD

**Issue by grumo35** [threathunters-io/laurel#138]
Hi,

while i have auditd configured with log_format=ENRICHED i do get arch and uids translated ARCH=x86_64 SYSCALL=execve
 
While Laurel doesnt. 

config.toml

```TOML
[translate]

# Perform translations of numeric values that can also be done by
# auditd if configured with log_format=ENRICHED.

# arch, syscall, sockaddr structures
universal = true
# UID, GID values
user-db = true
```

Do i miss something ? I've tried restarting several times no improvments
