### ISSUE TITLE
[question] How to forward to or call another script/process.

### ISSUE THREAD

**Issue by bobbintb** [threathunters-io/laurel#223]
This is probably a stupid question but how do I pass the data laurel has processed to another process? Just pipe it? Previously my auditd plugin just called a script that had to parse that awful format and then take action on certain events. Now that laurel parses it into JSON, I need to pass it to my script. I thought there would be an option in the laurel config file but there isn't. I'm not overlooking anything, am I?

**Comment by hillu** [comment]
So far, there is no such option. Right now, you could do do something like
```
tail --follow=name /var/log/laurel/audit.log | your-script
```

**Comment by bobbintb** [comment]
Is it possible to do it from stdout instead of the log? I was thinking laurel would act as a middle man between auditspd and my script so instead of my script reading stdin from the auditspd plugin, it read read from laurel's stdout. Can I add a pipe to the command or argument in the plugin definition file?

**Comment by hillu** [comment]
Writing to stdout is possible, see the comment in the example config file:
``` toml
[auditlog]
# Base file name for the JSONL-based log file. Set to "-" to log to stdout. In this case 
# other log file related settings will be ignored.
file = "audit.log"
```
